<link rel="stylesheet" href="{{ asset('dist-front/css/bootstrap.min.css') }}">
<link rel="stylesheet" href="{{ asset('dist-front/css/jquery-ui.css') }}">
<link rel="stylesheet" href="{{ asset('dist-front/css/animate.min.css') }}">
<link rel="stylesheet" href="{{ asset('dist-front/css/magnific-popup.css') }}">
<link rel="stylesheet" href="{{ asset('dist-front/css/owl.carousel.min.css') }}">
<link rel="stylesheet" href="{{ asset('dist-front/css/select2.min.css') }}">
<link rel="stylesheet" href="{{ asset('dist-front/css/select2-bootstrap.min.css') }}">
<link rel="stylesheet" href="{{ asset('dist-front/css/sweetalert2.min.css') }}">
<link rel="stylesheet" href="{{ asset('dist-front/css/spacing.css') }}">
<link rel="stylesheet" href="{{ asset('dist-front/css/font-awesome.min.css') }}">
<link rel="stylesheet" href="{{ asset('dist-front/css/daterangepicker.css') }}">
<link rel="stylesheet" href="{{ asset('dist-front/css/meanmenu.css') }}">
<link rel="stylesheet" href="{{ asset('dist-front/css/iziToast.min.css') }}">
<link rel="stylesheet" href="{{ asset('dist-front/css/style.css') }}">
<link rel="stylesheet" href="{{ asset('dist/css/bootstrap.min.css') }}">
<link rel="stylesheet" href="{{ asset('dist/css/font-awesome.min.css') }}">
<link rel="stylesheet" href="{{ asset('dist/css/select2.min.css') }}">
<link rel="stylesheet" href="{{ asset('dist/css/bootstrap-datepicker.min.css') }}">
<link rel="stylesheet" href="{{ asset('dist/css/bootstrap-timepicker.min.css') }}">
<link rel="stylesheet" href="{{ asset('dist/css/bootstrap-tagsinput.css') }}">
<link rel="stylesheet" href="{{ asset('dist/css/duotone-dark.css') }}">
<link rel="stylesheet" href="{{ asset('dist/css/dataTables.bootstrap4.min.css') }}">
<link rel="stylesheet" href="{{ asset('dist/css/iziToast.min.css') }}">
<link rel="stylesheet" href="{{ asset('dist/css/fontawesome-iconpicker.min.css') }}">
<link rel="stylesheet" href="{{ asset('dist/css/bootstrap4-toggle.min.css') }}">
<link rel="stylesheet" href="{{ asset('dist/css/summernote-bs4.css') }}">

<link rel="stylesheet" href="{{ asset('dist/css/components.css') }}">

<link rel="stylesheet" href="{{ asset('dist/css/custom.css') }}">